name = "admin-selify-ai"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".svelte-kit/cloudflare"

[vars]
PUBLIC_SUPABASE_URL = "https://api.selify.ai"
PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiYW5vbiIsImlzcyI6InN1cGFiYXNlIiwiaWF0IjoxNzU5MTA0MDAwLCJleHAiOjE5MTY4NzA0MDB9.6R-NBkGVMauJV007j1ynQuOoaJwPRkZhADaVIx1e5mw"
API_BASE_URL = "https://api.selify.ai"
EMAIL_ENCRYPTION_KEY = "ibKStyZQUhhXCBEr8rQUODd08N2/X3Q0oYGJ/dTVsTw="
SUPABASE_SERVICE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoic2VydmljZV9yb2xlIiwiaXNzIjoic3VwYWJhc2UiLCJpYXQiOjE3NTkxMDQwMDAsImV4cCI6MTkxNjg3MDQwMH0.DfQ--FJKxIF_5nOV_iK4JrqTSWh49-eGrwD_qR1NcWI"
