name = "admin-selify-ai"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".svelte-kit/cloudflare"

[vars]
PUBLIC_SUPABASE_URL = "https://api.selify.ai"
PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiYW5vbiIsImlzcyI6InN1cGFiYXNlIiwiaWF0IjoxNzU5MTA0MDAwLCJleHAiOjE5MTY4NzA0MDB9.6R-NBkGVMauJV007j1ynQuOoaJwPRkZhADaVIx1e5mw"
API_BASE_URL = "https://api.selify.ai"
